### ISSUE TITLE
Implement error/warning rules that HTML CodeSniffer implements

### ISSUE THREAD

**Issue by rowanmanning** [nature/pa11y#48]
The following list is taken roughly from HTML CodeSniffer's implemented rules. We should aim to implement tests for all of these in pa11y 2.0 as a baseline.

I've excluded notices for now to focus on *actionable* items.

- [ ] 1.1.1 Non-text content
  - [x] missing `alt` attribute on `img` (error)
  - [x] empty `alt` attribute on `img` inside an `a` with no other content (error)
  - [x] empty `alt` attribute on `img` but `title` attribute is set (error)
  - [x] missing `alt` attribute on `input type="image"` (error)
  - [ ] missing `alt` attribute on `area` (error)

**todo:** continue adding these, also get unique codes for each
